#!/bin/bash
set -euo pipefail

RESULTS_DIR=$1
MULTIQC_CONFIG=$2

echo "Generating MultiQC report"

# GROUP 5 - WRITE HERE THE COMMAND TO RUN MULTIQC
# THE MULTIQC COMMAND SHOULD TAKE THE RESULTS DIRECTORY AS INPUT, THE MULTIQC CONFIG FILE AS CONFIG, AND OUTPUT THE REPORT TO $RESULTS_DIR/multiqc_report


echo "Report assets copied"
